# Generated by Django 3.0.6 on 2020-05-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherreview',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facebook_messenger',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.GenderType'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linked_in',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ReviewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Teacher')),
                ('teacher_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.TeacherReview')),
            ],
        ),
    ]
