# Generated by Django 3.0.6 on 2020-05-18 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200516_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaigncourse',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='campaigncourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribe_type',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='campaign',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Subscription'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facebook_messenger',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='teacherfollow',
            table='teacher_followers',
        ),
        migrations.DeleteModel(
            name='CampaignCourse',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
        migrations.AlterField(
            model_name='teacherreview',
            name='teacher_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.TeacherRating'),
        ),
    ]
