# Generated by Django 3.0.6 on 2020-05-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200518_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'social_types',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='social_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SocialType'),
        ),
    ]
