# Generated by Django 3.0.6 on 2020-05-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistfollower',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Teacher'),
        ),
        migrations.AddField(
            model_name='middlecontenttag',
            name='Content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Content'),
        ),
        migrations.AddField(
            model_name='middlecontenttag',
            name='middle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.MiddleCategory'),
        ),
        migrations.AddField(
            model_name='middlecategory',
            name='root_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.RootCategory'),
        ),
        migrations.AddField(
            model_name='endcontenttag',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Content'),
        ),
        migrations.AddField(
            model_name='endcontenttag',
            name='end_categorry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.EndCategory'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Course'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.CourseRating'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.PaymentStatus'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Teacher'),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Content'),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='content_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContentRating'),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='content',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ActivityType'),
        ),
        migrations.AddField(
            model_name='content',
            name='meditaion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContentType'),
        ),
        migrations.AddField(
            model_name='content',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Target'),
        ),
        migrations.AddField(
            model_name='content',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Teacher'),
        ),
    ]
