# Generated by Django 3.0.6 on 2020-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200515_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterModelTable(
            name='contenttype',
            table='content_types',
        ),
    ]
