# Generated by Django 3.0.6 on 2020-05-18 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200516_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='meditaion_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='middlecontenttag',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='playlistgroup',
            old_name='content',
            new_name='content_is',
        ),
        migrations.AddField(
            model_name='content',
            name='course_img',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endcategory',
            name='middle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.MiddleCategory'),
        ),
        migrations.AlterField(
            model_name='content',
            name='running_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='contenttype',
            table='meditation_types',
        ),
    ]
