# Generated by Django 3.0.6 on 2020-05-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200518_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistgroup',
            old_name='content_is',
            new_name='content',
        ),
        migrations.AlterModelTable(
            name='contenttype',
            table='content_types',
        ),
    ]
